export const teamMembers = [
  { name: 'Ing. Ivo Tirol', role: 'Výkonný ředitel, ekonom', email: 'office@bestaccount.cz' },
  { name: 'Ing. Tereza Tirolová', role: 'Jednatelka, daňová poradkyně, členka KDP ČR, poradce č. 5270', email: 'office@bestaccount.cz' },
  { name: 'Ing. Martin Coufal', role: 'Externí auditor, daňový poradce č. 1721', email: null },
  { name: 'Ing. Aleš Coufal', role: 'Externí daňový poradce č. 4561', email: null },
  { name: 'Jana Pichoňská', role: 'Senior účetní, správce účetních software', email: 'admin@bestaccount.cz' },
  { name: 'Šimon Tirol', role: 'Asistentka vedení společnosti', email: 'sekretariat@bestaccount.cz' },
  { name: 'Bc. Zuzana Schabjuková', role: 'Senior účetní', email: 'fakturace@bestaccount.cz' },
  { name: 'Petr Zbedina', role: 'Senior účetní', email: 'petr.zbedina@bestaccount.cz' },
  { name: 'Michal Bek', role: 'Účetní', email: 'opava@bestaccount.cz' },
  { name: 'Marek Hořín', role: 'Účetní', email: 'fakturace@bestaccount.cz' },
  { name: 'Ing. Martina Draisaitlová', role: 'Účetní', email: 'martina.draisaitlova@bestaccount.cz' },
  { name: 'Andrea Vojtěchová', role: 'Účetní', email: 'fakturace@bestaccount.cz' },
  { name: 'Josef Bajer', role: 'Účetní', email: 'fakturace@bestaccount.cz' },
  { name: 'Sandra Orlíková', role: 'Účetní', email: 'opava@bestaccount.cz' },
  { name: 'Ing. Lucie Neuwirthová', role: 'Účetní', email: 'lucie.neuwirthova@bestaccount.cz' },
  { name: 'Eva Slámová', role: 'Administrativa', email: 'fakturace@bestaccount.cz' },
  { name: 'Anna Dusková', role: 'Administrativní výpomoc', email: 'fakturace@bestaccount.cz' },
  { name: 'Ing. Radomír Wisnar', role: 'Účetní', email: 'radomir.wisnar@bestaccount.cz' },
  { name: 'Dáša Vandasová', role: 'BOZP a PO, OŽP, RTZZ — členka Komory České republiky pro BOZP a PO', email: 'dasa.vandasova@gmail.com' },
  { name: 'Barbora Nekorancová', role: 'Mzdová účetní', email: 'personalistika@bestaccount.cz' },
  { name: 'Ing. Vladimíra Šimečková', role: 'Mzdová účetní', email: 'mzdy@bestaccount.cz' },
  { name: 'Hana Mičanová', role: 'Mzdová účetní', email: null },
];
