export const teamMembers = [
  { name: 'Ing. Ivo Tirol', roleKey: 'team.role.ivo_tirol', email: 'office@bestaccount.cz' },
  { name: 'Ing. Tereza Tirolová', roleKey: 'team.role.tereza_tirolova', email: 'office@bestaccount.cz' },
  { name: 'Ing. Martin Coufal', roleKey: 'team.role.martin_coufal', email: null },
  { name: 'Ing. Aleš Coufal', roleKey: 'team.role.ales_coufal', email: null },
  { name: 'Jana Pichoňská', roleKey: 'team.role.jana_pichonska', email: 'admin@bestaccount.cz' },
  { name: 'Šimon Tirol', roleKey: 'team.role.simon_tirol', email: 'sekretariat@bestaccount.cz' },
  { name: 'Bc. Zuzana Schabjuková', roleKey: 'team.role.zuzana_schabjukova', email: 'fakturace@bestaccount.cz' },
  { name: 'Petr Zbedina', roleKey: 'team.role.petr_zbedina', email: 'petr.zbedina@bestaccount.cz' },
  { name: 'Michal Bek', roleKey: 'team.role.michal_bek', email: 'opava@bestaccount.cz' },
  { name: 'Marek Hořín', roleKey: 'team.role.marek_horin', email: 'fakturace@bestaccount.cz' },
  { name: 'Ing. Martina Draisaitlová', roleKey: 'team.role.martina_draisaitlova', email: 'martina.draisaitlova@bestaccount.cz' },
  { name: 'Andrea Vojtěchová', roleKey: 'team.role.andrea_vojtechova', email: 'fakturace@bestaccount.cz' },
  { name: 'Josef Bajer', roleKey: 'team.role.josef_bajer', email: 'fakturace@bestaccount.cz' },
  { name: 'Sandra Orlíková', roleKey: 'team.role.sandra_orlikova', email: 'opava@bestaccount.cz' },
  { name: 'Ing. Lucie Neuwirthová', roleKey: 'team.role.lucie_neuwirthova', email: 'lucie.neuwirthova@bestaccount.cz' },
  { name: 'Eva Slámová', roleKey: 'team.role.eva_slamova', email: 'fakturace@bestaccount.cz' },
  { name: 'Anna Dusková', roleKey: 'team.role.anna_duskova', email: 'fakturace@bestaccount.cz' },
  { name: 'Ing. Radomír Wisnar', roleKey: 'team.role.radomir_wisnar', email: 'radomir.wisnar@bestaccount.cz' },
  { name: 'Dáša Vandasová', roleKey: 'team.role.dasa_vandasova', email: 'dasa.vandasova@gmail.com' },
  { name: 'Barbora Nekorancová', roleKey: 'team.role.barbora_nekorancova', email: 'personalistika@bestaccount.cz' },
  { name: 'Ing. Vladimíra Šimečková', roleKey: 'team.role.vladimira_simeckova', email: 'mzdy@bestaccount.cz' },
  { name: 'Hana Mičanová', roleKey: 'team.role.hana_micanova', email: null },
];